import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../domain/models/statement_data.dart';
import 'widgets/pdf_budget_summary.dart';
import 'widgets/pdf_category_summary.dart';
import 'widgets/pdf_header.dart';
import 'widgets/pdf_summary.dart';
import 'widgets/pdf_transaction_notes.dart';
import 'widgets/pdf_transactions.dart';

class PdfGenerator {
  Future<Uint8List> generate(
      StatementData statement,
      ) async {
    final regularFont =
    await PdfGoogleFonts.notoSansRegular();

    final boldFont =
    await PdfGoogleFonts.notoSansBold();

    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: regularFont,
        bold: boldFont,
      ),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,

        margin: const pw.EdgeInsets.all(
          32,
        ),

        footer: (context) {
          return pw.Container(
            margin: const pw.EdgeInsets.only(
              top: 16,
            ),
            child: pw.Row(
              mainAxisAlignment:
              pw.MainAxisAlignment.spaceBetween,
              children: [

                pw.Text(
                  'Generated by PocketIQ',
                  style: const pw.TextStyle(
                    fontSize: 9,
                  ),
                ),

                pw.Text(
                  'Page ${context.pageNumber} of ${context.pagesCount}',
                  style: const pw.TextStyle(
                    fontSize: 9,
                  ),
                ),
              ],
            ),
          );
        },

        build: (_) {
          final content = <pw.Widget>[

            PdfHeader.build(
              statement,
            ),

            pw.SizedBox(
              height: 20,
            ),

            PdfSummary.build(
              statement,
            ),

            pw.SizedBox(
              height: 20,
            ),

            pw.Text(
              'Transactions',
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.SizedBox(
              height: 8,
            ),

            PdfTransactions.build(
              statement,
            ),
          ];

          if (statement.categories.isNotEmpty) {
            content.add(
              pw.Padding(
                padding: const pw.EdgeInsets.only(
                  top: 20,
                ),
                child: PdfCategorySummary.build(
                  statement,
                ),
              ),
            );
          }

          if (statement.budgets.isNotEmpty) {
            content.add(
              pw.Padding(
                padding: const pw.EdgeInsets.only(
                  top: 20,
                ),
                child: PdfBudgetSummary.build(
                  statement,
                ),
              ),
            );
          }

          if (statement.notedTransactions.isNotEmpty) {
            content.add(
              pw.Padding(
                padding: const pw.EdgeInsets.only(
                  top: 20,
                ),
                child: PdfTransactionNotes.build(
                  statement,
                ),
              ),
            );
          }

          return content;
        },
      ),
    );

    return pdf.save();
  }
}